I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 18, in script
    define medBubble = Character(None, image="lucy", kind=bubble)   # Lucy
  File "game/script.rpy", line 18, in script
    define medBubble = Character(None, image="lucy", kind=bubble)   # Lucy
  File "game/script.rpy", line 18, in <module>
    define medBubble = Character(None, image="lucy", kind=bubble)   # Lucy
TypeError: __init__() got an unexpected keyword argument 'kind'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Informatique\Mon Drive\Quentin\Ateliers\MiniLab Enfants\Moliere\renpy-8.0.3-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\Informatique\Mon Drive\Quentin\Ateliers\MiniLab Enfants\Moliere\renpy-8.0.3-sdk\renpy\main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 18, in script
    define medBubble = Character(None, image="lucy", kind=bubble)   # Lucy
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/script.rpy", line 18, in script
    define medBubble = Character(None, image="lucy", kind=bubble)   # Lucy
  File "C:\Users\Informatique\Mon Drive\Quentin\Ateliers\MiniLab Enfants\Moliere\renpy-8.0.3-sdk\renpy\ast.py", line 2441, in execute
    self.set()
  File "C:\Users\Informatique\Mon Drive\Quentin\Ateliers\MiniLab Enfants\Moliere\renpy-8.0.3-sdk\renpy\ast.py", line 2455, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Informatique\Mon Drive\Quentin\Ateliers\MiniLab Enfants\Moliere\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 18, in <module>
    define medBubble = Character(None, image="lucy", kind=bubble)   # Lucy
  File "C:\Users\Informatique\Mon Drive\Quentin\Ateliers\MiniLab Enfants\Moliere\renpy-8.0.3-sdk\renpy\character.py", line 1580, in Character
    return type(kind)(name, kind=kind, **properties)
TypeError: __init__() got an unexpected keyword argument 'kind'

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
OKDATA 1.0
Thu Nov 16 14:36:11 2023
