I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 275, in script
    python:
  File "renpy/common/00start.rpy", line 275, in script
    python:
  File "renpy/common/00start.rpy", line 279, in <module>
    renpy.call_in_new_context("_main_menu")
  File "renpy/common/00start.rpy", line 292, in script
    python:
  File "renpy/common/00start.rpy", line 292, in script
    python:
  File "renpy/common/00start.rpy", line 295, in <module>
    _enter_menu()
  File "renpy/common/00gamemenu.rpy", line 85, in _enter_menu
    renpy.take_screenshot((config.thumbnail_width, config.thumbnail_height))
error: Out of memory

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\main.py", line 670, in main
    run(restart)
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\main.py", line 144, in run
    renpy.execution.run_context(True)
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 275, in script
    python:
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "renpy/common/00start.rpy", line 275, in script
    python:
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 279, in <module>
    renpy.call_in_new_context("_main_menu")
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\game.py", line 349, in call_in_new_context
    return renpy.execution.run_context(False)
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 292, in script
    python:
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "renpy/common/00start.rpy", line 292, in script
    python:
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 295, in <module>
    _enter_menu()
  File "renpy/common/00gamemenu.rpy", line 85, in _enter_menu
    renpy.take_screenshot((config.thumbnail_width, config.thumbnail_height))
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\exports.py", line 1881, in take_screenshot
    renpy.game.interface.take_screenshot(scale, background=background)
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\display\core.py", line 2839, in take_screenshot
    surf = renpy.display.draw.screenshot(self.surftree)
  File "gl2draw.pyx", line 1120, in renpy.gl2.gl2draw.GL2Draw.screenshot
  File "C:\Users\Informatique\Documents\renpy-8.1.3-sdk\renpy\display\pgrender.py", line 116, in surface
    surf = Surface((width + 4, height + 4), 0, sample) # type:ignore
  File "src/pygame_sdl2/surface.pyx", line 164, in pygame_sdl2.surface.Surface.__init__
error: Out of memory

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
OKDATA 1.0
Thu Nov 23 14:35:43 2023
